# Generated by Django 4.2.9 on 2026-02-01 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('google_oauth_token', models.TextField()),
                ('notion_api_token', models.TextField()),
                ('notion_database_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('keep_note_id', models.CharField(max_length=255)),
                ('notion_page_id', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now_add=True)),
                ('keep_modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sync_state',
                'indexes': [models.Index(fields=['user_id', 'keep_note_id'], name='idx_sync_state_user_note')],
                'unique_together': {('user_id', 'keep_note_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.UUIDField()),
                ('keep_note_id', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_id'], name='idx_sync_logs_job_id')],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('full_sync', models.BooleanField(default=False)),
                ('total_notes', models.IntegerField(default=0)),
                ('processed_notes', models.IntegerField(default=0)),
                ('failed_notes', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='idx_sync_jobs_user_created')],
            },
        ),
    ]
